version: '3'
services:

  web:
    container_name: web
    image: developercovy/example-docker:1.0
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: developercovy/example-docker-nginx:1.0
    ports:
      - 80:80
    depends_on:
      - web